// Generated by CoffeeScript 1.10.0
'use strict';
var now;

if (performance && performance.now) {
  now = function() {
    return performance.now();
  };
} else if (Date.now) {
  now = function() {
    return Date.now();
  };
} else {
  now = function() {
    return (new Date).getTime();
  };
}

module.exports = class LapTimer{
  constructor(output){
    this.output = output;
  }
  
  start(){
    this.start_time = this.lap_time = now();
  }
  
  lap(message){
    var current = now();
    this.output(message + ": " + (current - this.lap_time) + " ms");
    this.lap_time = current;
  }
  
  finish(message){
    if (message) {
      this.lap(message);
    }
    this.output("合計時間: " + (this.lap_time - this.start_time) + " ms");
  }
  
};
